### PR TITLE
ability to add extra headers while sending the request

### PR DESCRIPTION
**Pull request by devqore**
When I'm trying to access the Jenkins instance which is behind [Google Cloud IAP with additional headers](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_proxy-authorization_header) as follows:
```python
server = Jenkins("https://jenkins.behind.iap", auth=('xxx', 'yyy'),
                 headers={"Proxy-Authorization": "Bearer zzz"})
job = server.get_job('some-job')
```

I'm getting the exception:
```
Traceback (most recent call last):
  File "/xxx/venv/lib/python3.9/site-packages/api4jenkins/item.py", line 71, in handle_req
    return self.jenkins.send_req(method, self.url + entry, **kwargs)
  File "/xxx/venv/lib/python3.9/site-packages/api4jenkins/requester.py", line 27, in send
    resp = session.request(method, url, **kwargs, **kw)
TypeError: requests.sessions.Session.request() got multiple values for keyword argument 'headers'
```
This pull request solves the problem and additional headers might be added.

### CODE REVIEW

**Comment by joelee2012** [comment]
@devqore are you able to update version and history  ?

**Comment by devqore** [comment]
@joelee2012 thanks for checking. The release history was updated, and the version was bumped by one patch number, is this ok?

**Comment by joelee2012** [comment]
@devqore great

**Comment by joelee2012** [comment]
new release [v1.14.1](https://github.com/joelee2012/api4jenkins/releases/tag/v1.14.1) has been created

**Pull request merged**
